package ventanas;

import Controlador.CtrlUsuarioEmpleado;
import clases.validaciones;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Empleado;

public class FrmLoginRegistrarEmpleado extends javax.swing.JFrame {

    validaciones vali = new validaciones();

    CtrlUsuarioEmpleado ctrlUsuarioEmpleado;
    SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd");
    //Claave de verificacion 
    String clave_verificacion = "1234";

    public FrmLoginRegistrarEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        obtenerFechaActual();
         setIconImage(new ImageIcon(getClass().getResource("/Imagenes/AguaIcono.png")).getImage());
        //Validaciones de los campos
        vali.ValidarNumeros(txtCedulaEmpleado);
        vali.LimitarCaracteres(txtCedulaEmpleado, 10);
        vali.ValidarLetras(txtNombreEmpleado);
        vali.ValidarLetras(txtApellidoEmpleado);
        vali.ValidarLetras(txtDireccionEmpleado);
        vali.ValidarNumeros(txtTelefonoEmpleado);
        vali.LimitarCaracteres(txtTelefonoEmpleado, 7);
    }

    //Método para obtener la fecha actual
    public void obtenerFechaActual() {
        Calendar c = new GregorianCalendar();
        String dia = Integer.toString(c.get(Calendar.DATE));
        String mes = Integer.toString(c.get(Calendar.MONTH) + 1);
        String año = Integer.toString(c.get(Calendar.YEAR));
        txt_fechacreacion_usuario.setText(año + "-" + mes + "-" + dia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jb_registrarse = new javax.swing.JButton();
        txtCedulaEmpleado = new javax.swing.JTextField();
        jb_cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_fechacreacion_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccionEmpleado = new javax.swing.JTextField();
        txtCorreoEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtApellidoEmpleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefonoEmpleado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cFechaEmpleado = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jcbCargo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre_usuario = new javax.swing.JTextField();
        lbl_clave1 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRARSE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jb_registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarioagg.png"))); // NOI18N
        jb_registrarse.setText("REGISTRARSE");
        jb_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_registrarseActionPerformed(evt);
            }
        });
        jPanel1.add(jb_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        txtCedulaEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(txtCedulaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 168, -1));

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        jb_cancelar.setText("CANCELAR");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cedula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txt_fechacreacion_usuario.setEnabled(false);
        jPanel1.add(txt_fechacreacion_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 142, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Fecha de creacion de Usuario: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel1.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 168, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Direccion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));
        jPanel1.add(txtDireccionEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 322, -1));
        jPanel1.add(txtCorreoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 168, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Correo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Apellido:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(txtApellidoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 168, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Telefono:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));
        jPanel1.add(txtTelefonoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 322, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));
        jPanel1.add(cFechaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 322, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Cargo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Presidente", "Tesorero" }));
        jPanel1.add(jcbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 322, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nombre de Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel1.add(txt_nombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 183, -1));

        lbl_clave1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_clave1.setText("Clave:");
        jPanel1.add(lbl_clave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 39, -1));
        jPanel1.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 183, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        FrmLogin v = new FrmLogin();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_registrarseActionPerformed
         if (!txtCedulaEmpleado.equals("") && !txtNombreEmpleado.equals("") && !txtApellidoEmpleado.equals("")
                && cFechaEmpleado.getDate() != null && !txt_fechacreacion_usuario.equals("") && !txtDireccionEmpleado.equals("")
                && !txtTelefonoEmpleado.equals("") && !txtCorreoEmpleado.equals("") && !jcbCargo.getSelectedItem().toString().equals("Seleccione")
                && !txt_nombre_usuario.equals("") && !txt_clave.equals("")) {
            //Mensaje de petición de clave de verificación
            String clave = JOptionPane.showInputDialog("Clave de confirmacion");
            //Compara si la clave ingresada y la de verificación son iguales
            if (clave.equals(clave_verificacion)) {
                ctrlUsuarioEmpleado = new CtrlUsuarioEmpleado();
                Empleado empleado = new Empleado();
                empleado.setCedula(txtCedulaEmpleado.getText());
                empleado.setNombre(txtNombreEmpleado.getText());
                empleado.setApellido(txtApellidoEmpleado.getText());
                String fecha = formato.format(cFechaEmpleado.getDate());
                empleado.setFechaNacimiento(fecha);
                empleado.setFechaCreacion(txt_fechacreacion_usuario.getText());
                empleado.setDireccion(txtDireccionEmpleado.getText());
                empleado.setTelefono(txtTelefonoEmpleado.getText());
                empleado.setCorreo(txtCorreoEmpleado.getText());
                empleado.setCargo(jcbCargo.getSelectedItem().toString());
                empleado.setUsuario(txt_nombre_usuario.getText());
                empleado.setClave(txt_clave.getText());
                ctrlUsuarioEmpleado.guardarUsuarioEmpleado(empleado);
            }else{
                JOptionPane.showMessageDialog(null, "Clave de verificacion incorrecta.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llene todos los datos.");
        }
    }//GEN-LAST:event_jb_registrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginRegistrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginRegistrarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser cFechaEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_registrarse;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JLabel lbl_clave1;
    private javax.swing.JTextField txtApellidoEmpleado;
    public javax.swing.JTextField txtCedulaEmpleado;
    public javax.swing.JTextField txtCorreoEmpleado;
    public javax.swing.JTextField txtDireccionEmpleado;
    public javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtTelefonoEmpleado;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JTextField txt_fechacreacion_usuario;
    private javax.swing.JTextField txt_nombre_usuario;
    // End of variables declaration//GEN-END:variables
}
