package ventanas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modeloDAO.UsuarioEmpleadoDAO;

public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/AguaIcono.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jb_iniciarsesion = new javax.swing.JButton();
        txt_registrarse = new javax.swing.JLabel();
        txt_clave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loginuser.png"))); // NOI18N
        jLabel3.setText("INICIO  SESION");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 80));

        jb_iniciarsesion.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        jb_iniciarsesion.setText("INICIAR SESION");
        jb_iniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_iniciarsesionActionPerformed(evt);
            }
        });
        jPanel3.add(jb_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        txt_registrarse.setBackground(new java.awt.Color(255, 255, 255));
        txt_registrarse.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        txt_registrarse.setForeground(new java.awt.Color(0, 51, 153));
        txt_registrarse.setText("Registrarse");
        txt_registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_registrarseMouseClicked(evt);
            }
        });
        jPanel3.add(txt_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 70, 20));
        jPanel3.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        jLabel1.setText("Usuario");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 11)); // NOI18N
        jLabel2.setText("Contraseña");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));
        jPanel3.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_iniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_iniciarsesionActionPerformed
        UsuarioEmpleadoDAO DAO = new UsuarioEmpleadoDAO();
        //LLama al metodo de iniciar sesion
        Boolean sesion = DAO.iniciar_sesion(txt_usuario.getText(), txt_clave.getText());
        //Si sesion en true
        if (sesion) {
            //Abre el menu peincipal
            FrmMenuPrincipal m = new FrmMenuPrincipal();
            m.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Uusario o contraseña incorrectas.");
        }
    }//GEN-LAST:event_jb_iniciarsesionActionPerformed

    private void txt_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_registrarseMouseClicked
        FrmLoginRegistrarEmpleado v = new FrmLoginRegistrarEmpleado();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txt_registrarseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jb_iniciarsesion;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JLabel txt_registrarse;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
