/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class VistaCorreo extends javax.swing.JFrame {

    /**
     * Creates new form VistaCorreo
     */
    public VistaCorreo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pl_fondo = new javax.swing.JPanel();
        pl_bandeja = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_bandeja = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        pl_enviarcorreo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_destinatario = new javax.swing.JTextField();
        txt_remitente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_destinatariocopia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_asunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_mensaje = new javax.swing.JTextArea();
        btn_archivo = new javax.swing.JButton();
        btn_enviar = new javax.swing.JButton();
        lbl_mensajearchivo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_contraseña = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        item_salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        item_enviar = new javax.swing.JMenuItem();
        item_recibir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pl_bandeja.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bandeja.setColumns(20);
        txt_bandeja.setRows(5);
        jScrollPane2.setViewportView(txt_bandeja);

        pl_bandeja.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 59, 500, 349));

        jLabel6.setText("Bandeja de Entrada");
        pl_bandeja.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 34, -1, -1));

        pl_enviarcorreo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("De:");
        pl_enviarcorreo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 28, 47, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CC:");
        pl_enviarcorreo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 89, 47, 27));
        pl_enviarcorreo.add(txt_destinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 60, 445, -1));
        pl_enviarcorreo.add(txt_remitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 30, 228, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Para:");
        pl_enviarcorreo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 56, 47, 27));
        pl_enviarcorreo.add(txt_destinatariocopia, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 93, 445, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Asunto: ");
        pl_enviarcorreo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 122, -1, 27));
        pl_enviarcorreo.add(txt_asunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 126, 435, -1));

        txt_mensaje.setColumns(20);
        txt_mensaje.setRows(5);
        jScrollPane1.setViewportView(txt_mensaje);

        pl_enviarcorreo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, 496, 189));

        btn_archivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_archivo.setText("Adjuntar Archivo...");
        pl_enviarcorreo.add(btn_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 367, 144, -1));

        btn_enviar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_enviar.setText("Enviar");
        pl_enviarcorreo.add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 367, 69, -1));

        lbl_mensajearchivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_mensajearchivo.setText("(0) archivos adjuntos");
        pl_enviarcorreo.add(lbl_mensajearchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 408, 254, -1));

        jLabel5.setText("Contraseña");
        pl_enviarcorreo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 33, -1, -1));
        pl_enviarcorreo.add(txt_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 30, 147, -1));

        javax.swing.GroupLayout pl_fondoLayout = new javax.swing.GroupLayout(pl_fondo);
        pl_fondo.setLayout(pl_fondoLayout);
        pl_fondoLayout.setHorizontalGroup(
            pl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_fondoLayout.createSequentialGroup()
                .addComponent(pl_enviarcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(pl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pl_fondoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pl_bandeja, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pl_fondoLayout.setVerticalGroup(
            pl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pl_fondoLayout.createSequentialGroup()
                .addComponent(pl_enviarcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(pl_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pl_fondoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pl_bandeja, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jMenu1.setText("Archivo");

        item_salir.setText("Salir");
        jMenu1.add(item_salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        item_enviar.setText("Enviar");
        jMenu2.add(item_enviar);

        item_recibir.setText("Recibir");
        jMenu2.add(item_recibir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pl_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_archivo;
    public javax.swing.JButton btn_enviar;
    public javax.swing.JMenuItem item_enviar;
    public javax.swing.JMenuItem item_recibir;
    public javax.swing.JMenuItem item_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbl_mensajearchivo;
    public javax.swing.JPanel pl_bandeja;
    public javax.swing.JPanel pl_enviarcorreo;
    private javax.swing.JPanel pl_fondo;
    public javax.swing.JTextField txt_asunto;
    public javax.swing.JTextArea txt_bandeja;
    public javax.swing.JPasswordField txt_contraseña;
    public javax.swing.JTextField txt_destinatario;
    public javax.swing.JTextField txt_destinatariocopia;
    public javax.swing.JTextArea txt_mensaje;
    public javax.swing.JTextField txt_remitente;
    // End of variables declaration//GEN-END:variables
}
